#!/bin/bash

### This script is called after the user change environment variables in application setting page.

source "/var/apps/${TRIM_APPNAME}/cmd/common"

DOWNLOAD_DIR="${TRIM_PKGVAR}"
# 获取向导输入，去空格
openlist_http_port=$(str_trim "$openlist_http_port")
openlist_admin_password=$(str_trim "$openlist_admin_password")
openlist_version=$(str_trim "$openlist_version")
download_proxy_url=$(str_trim "$download_proxy_url")


get_openlist_download_url(){
    # 获取系统架构
    local arch
    local uname_out=$(uname -m)
    case "$uname_out" in
        x86_64) arch="linux-amd64" ;;
        aarch64) arch="linux-arm64" ;;
        # openlist不支持longarch64
        # loongarch64) arch="linux-loong64" ;;
        riscv64) arch="linux-riscv64" ;;
        *)
            alarm_and_exit "不支持当前系统架构 $uname_out 下载安装OpenList"
            ;;
    esac
    log_msg "系统架构: ${arch}"
    # 构造下载链接并下载安装
    local download_version="$1"
    local download_url
    if [[ "$download_version" == "beta" ]]; then
        download_url="https://github.com/OpenListTeam/OpenList/releases/download/beta/openlist-${arch}.tar.gz"
    else
        download_url="https://github.com/OpenListTeam/OpenList/releases/download/v${download_version}/openlist-${arch}.tar.gz"
    fi
    local proxy_url="$2"
    if [[ -z "${proxy_url}" ]]; then
        log_msg "使用代理下载 OpenList: ${proxy_url}"
        download_url="${proxy_url}/${download_url}"
    fi
    echo $download_url
}

check_url_availability() {
    local url="$1"
    local status_code=$(curl -I -s -o /dev/null -w "%{http_code}" "$url")

    if [ "$status_code" -ge 200 ] && [ "$status_code" -le 399 ]; then
        return 0  # URL 可用
    else
        log_msg "下载链接不可用，HTTP 状态码: $status_code, URL: $url"
        return 1  # URL 不可用
    fi
}

get_last_openlist_version(){
    # GitHub API URL
    api_url="https://api.github.com/repos/OpenListTeam/OpenList/releases/latest"
    # 使用 curl 获取 JSON 数据
    json_data=$(curl -s "$api_url")
    # 使用 grep 和 sed 提取版本号
    latest_version=$(echo "$json_data" | grep -oP '"tag_name": "\Kv[0-9]+\.[0-9]+\.[0-9]+' | head -1)
    # 去除版本号前的 'v'
    latest_version=${latest_version#v}
    # 输出最新版本号
    echo "$latest_version"
}

install_version(){
    local install_version="$1"
    if [[ -z "${install_version}" ]]; then
        log_msg "未指定OpenList版本号, 跳过安装指定版本"
        return 0
    fi
    log_msg "用户指定安装 OpenList 版本: ${install_version}"
    local current_version=$(${TRIM_APPDEST}/bin/openlist version | awk '/^Version:/{print $2}' | sed 's/^v//')
    if [[ "$current_version" == "refs/heads/main" ]]; then
        # beta 固定版本号是 refs/heads/main
        current_version="beta"
    fi
    if [ "$current_version" == "$install_version" ]; then
        log_msg "OpenList 当前已是 ${install_version} 版本，跳过安装指定版本"
        return 0
    fi

    log_msg "当前 OpenList 版本为 ${current_version}"
    local download_url=$(get_openlist_download_url ${install_version} "${download_proxy_url}")
    log_msg "检查下载链接: ${download_url}"
    if !(check_url_availability "${download_url}") ; then
        local latest_version=$(get_last_openlist_version)
        alarm_and_exit "OpenList最新版本号: $latest_version，请检测版本号或加速地址。下载链接不可用: ${download_url}"
    fi
    
    log_msg "开始下载OpenList: ${download_url}"
    local save_file="${DOWNLOAD_DIR}/openlist_${install_version}.tar.gz"
    rm -f $save_file
    wget -O $save_file "${download_url}"
    if [ ! -f $save_file ]; then
        local latest_version=$(get_last_openlist_version)
        alarm_and_exit "下载失败，请稍后重试或换其他加速地址。OpenList最新版本号: $latest_version，当次下载地址：${download_url}"
    fi

    log_msg "下载完成：${save_file}, 开始解压openlist程序文件"
    bash -c "tar -xzf $save_file -C ${DOWNLOAD_DIR}" >> ${LOG_FILE} 2>&1
    log_msg "尝试停止OpenList服务"
    bash -c "${TRIM_APPDEST}/bin/openlist stop" >> ${LOG_FILE} 2>&1
    log_msg "替换openlist程序文件"
    bash -c "mv ${DOWNLOAD_DIR}/openlist $TRIM_APPDEST/bin/openlist" >> ${LOG_FILE} 2>&1
    log_msg "已安装OpenList版本: $($TRIM_APPDEST/bin/openlist version | awk '/^Version:/{print $2}' | sed 's/^v//') 完成"
    rm -f $save_file
}


update_admin_password "$openlist_admin_password"
update_http_port "$openlist_http_port"
install_version "$openlist_version"

exit 0