#!/bin/bash

### This script is called after the user installs the application.

source "/var/apps/${TRIM_APPNAME}/cmd/common"

# 获取向导输入，去空格
openlist_admin_password=$(str_trim "$openlist_admin_password")
openlist_version=$(str_trim "$openlist_version")


update_admin_password "$openlist_admin_password"
update_http_port "$openlist_http_port"

exit 0