name: Daily check release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # 只需要读代码
      actions: write        # ← 关键：允许触发 workflow_dispatch
    steps:
      - uses: actions/checkout@v4 

      # ---------- 1. 读取上次的值 ----------
      - name: Try to download last artifact
        id: dl
        uses: actions/download-artifact@v4
        continue-on-error: true   # 第一次没有 artifact 会报错，忽略即可
        with:
          name: last-run
          path: .

      - name: Read last OpenList version
        id: last
        run: |
          if [ -f OpenListVersion.txt ]; then
            echo "version=$(cat OpenListVersion.txt)" >> $GITHUB_OUTPUT
          else
            echo "version=never" >> $GITHUB_OUTPUT
          fi
          
      - name: Check if need a new release
        id: need_release
        run: |
          LAST_VERSION="${{ steps.last.outputs.version }}"
          echo "上次构建OpenList版本: $LAST_VERSION"
          REAL_VERSION=$(curl -s "https://api.github.com/repos/OpenListTeam/OpenList/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' 2>/dev/null | grep . || echo "unknown")
          echo "获取最新OpenList版本: $REAL_VERSION"
          echo "version=$REAL_VERSION" >> $GITHUB_OUTPUT

          if [ "$LAST_VERSION" != "$REAL_VERSION" ]; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger release workflow
        if: steps.need_release.outputs.trigger == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run release.yml \
            --ref ${{ github.ref_name }}          
            
      - name: Save this OpenList version
        run: |
          echo "${{ steps.need_release.outputs.version }}" > OpenListVersion.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-run
          path: OpenListVersion.txt
          retention-days: 2